{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfailover.fullname" . }}
  {{- with .Values.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rfailover.selectorLabels" . | nindent 4 }}
{{- end -}}